# Soru1 : 
miuul_gezinomi.xlsx dosyasını okutunuz ve veri seti ile ilgili genel bilgileri gösteriniz.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_excel("C:/Users/HP-PC/Desktop/miuul_gezinomi.xlsx")
data.head()

,SaleId,SaleDate,CheckInDate,Price,ConceptName,SaleCityName,CInDay,SaleCheckInDayDiff,Seasons
0,415122,2022-12-03,2022-12-03,79.304029,Herşey Dahil,Antalya,Saturday,0,Low
1,415103,2022-12-03,2022-12-03,45.970696,Yarım Pansiyon,Antalya,Saturday,0,Low
2,404034,2022-09-12,2022-09-13,77.838828,Herşey Dahil,Antalya,Tuesday,1,High
3,415094,2022-12-03,2022-12-10,222.710623,Yarım Pansiyon,İzmir,Saturday,7,Low
4,414951,2022-12-01,2022-12-03,140.476190,Yarım Pansiyon,İzmir,Saturday,2,Low

Genel Bilgiler:

In [10]:
data.tail()

,SaleId,SaleDate,CheckInDate,Price,ConceptName,SaleCityName,CInDay,SaleCheckInDayDiff,Seasons
59159,51817,2016-01-05,2016-10-10,54.304636,Herşey Dahil,Antalya,Monday,279,Low
59160,51816,2016-01-05,2016-10-10,54.304636,Herşey Dahil,Antalya,Monday,279,Low
59161,51814,2016-01-05,2016-01-06,40.562914,Herşey Dahil,Diğer,Wednesday,1,Low
59162,51736,2016-01-04,2016-01-05,69.847682,Yarım Pansiyon,Diğer,Tuesday,1,Low
59163,51731,2016-01-04,2016-08-22,158.940397,Herşey Dahil,Antalya,Monday,231,High

In [11]:
data.shape

(59164, 9)

In [14]:
data.dtypes

SaleId                         int64
SaleDate              datetime64[ns]
CheckInDate           datetime64[ns]
Price                        float64
ConceptName                   object
SaleCityName                  object
CInDay                        object
SaleCheckInDayDiff             int64
Seasons                       object
dtype: object

In [15]:
data.columns

Index(['SaleId', 'SaleDate', 'CheckInDate', 'Price', 'ConceptName',
       'SaleCityName', 'CInDay', 'SaleCheckInDayDiff', 'Seasons'],
      dtype='object')

In [16]:
data.index

RangeIndex(start=0, stop=59164, step=1)

In [4]:
data["Price"].describe()

count    59151.000000
mean        61.345057
std         51.384617
min          0.000000
25%         35.343035
50%         54.261294
75%         77.962578
max       4880.471380
Name: Price, dtype: float64

In [21]:
data.isnull().values.any()

True

In [22]:
data.isnull().sum()

SaleId                 0
SaleDate               0
CheckInDate            0
Price                 13
ConceptName            0
SaleCityName           0
CInDay                 0
SaleCheckInDayDiff     0
Seasons                0
dtype: int64

In [25]:
data["ConceptName"].value_counts()

Herşey Dahil      53186
Yarım Pansiyon     3559
Oda + Kahvaltı     2419
Name: ConceptName, dtype: int64

In [51]:
data.head()

,SaleId,SaleDate,CheckInDate,Price,ConceptName,SaleCityName,CInDay,SaleCheckInDayDiff,Seasons
0,415122,2022-12-03,2022-12-03,79.304029,Herşey Dahil,Antalya,Saturday,0,Low
1,415103,2022-12-03,2022-12-03,45.970696,Yarım Pansiyon,Antalya,Saturday,0,Low
2,404034,2022-09-12,2022-09-13,77.838828,Herşey Dahil,Antalya,Tuesday,1,High
3,415094,2022-12-03,2022-12-10,222.710623,Yarım Pansiyon,İzmir,Saturday,7,Low
4,414951,2022-12-01,2022-12-03,140.476190,Yarım Pansiyon,İzmir,Saturday,2,Low

In [60]:
data.loc[0:4, 'SaleDate':'Price']

    SaleDate CheckInDate       Price
0 2022-12-03  2022-12-03   79.304029
1 2022-12-03  2022-12-03   45.970696
2 2022-09-12  2022-09-13   77.838828
3 2022-12-03  2022-12-10  222.710623
4 2022-12-01  2022-12-03  140.476190

In [59]:
data.iloc[2:4, 1:3]

    SaleDate CheckInDate
2 2022-09-12  2022-09-13
3 2022-12-03  2022-12-10

In [57]:
data.head()

,SaleId,SaleDate,CheckInDate,Price,ConceptName,SaleCityName,CInDay,SaleCheckInDayDiff,Seasons
0,415122,2022-12-03,2022-12-03,79.304029,Herşey Dahil,Antalya,Saturday,0,Low
1,415103,2022-12-03,2022-12-03,45.970696,Yarım Pansiyon,Antalya,Saturday,0,Low
2,404034,2022-09-12,2022-09-13,77.838828,Herşey Dahil,Antalya,Tuesday,1,High
3,415094,2022-12-03,2022-12-10,222.710623,Yarım Pansiyon,İzmir,Saturday,7,Low
4,414951,2022-12-01,2022-12-03,140.476190,Yarım Pansiyon,İzmir,Saturday,2,Low

In [61]:
"Price" in data

True

In [62]:
type(data["Price"].head())

pandas.core.series.Series

In [64]:
data[data["Price"]>45.970696]["Price"].count()

35826

# Soru 2:
Kaç unique şehir vardır? Frekansları nedir?

NOT:
Aradaki fark şudur: unique() işlevi, sütunun tüm benzersiz değerlerini bir dizi biçiminde döndürür. nunique() işlevi, tüm benzersiz değerlerin sayısını döndürür.

In [65]:
data.head()

,SaleId,SaleDate,CheckInDate,Price,ConceptName,SaleCityName,CInDay,SaleCheckInDayDiff,Seasons
0,415122,2022-12-03,2022-12-03,79.304029,Herşey Dahil,Antalya,Saturday,0,Low
1,415103,2022-12-03,2022-12-03,45.970696,Yarım Pansiyon,Antalya,Saturday,0,Low
2,404034,2022-09-12,2022-09-13,77.838828,Herşey Dahil,Antalya,Tuesday,1,High
3,415094,2022-12-03,2022-12-10,222.710623,Yarım Pansiyon,İzmir,Saturday,7,Low
4,414951,2022-12-01,2022-12-03,140.476190,Yarım Pansiyon,İzmir,Saturday,2,Low

In [521]:
data["SaleCityName"].nunique()

6

In [524]:
#Frekansları:
print(data["SaleCityName"].value_counts())

Antalya    31649
Muğla      10662
Aydın      10646
Diğer       3245
İzmir       2507
Girne        455
Name: SaleCityName, dtype: int64

# Soru 3: 
Kaç unique Concept vardır?

In [525]:
data["ConceptName"].nunique()

3

# Soru4: 
Hangi Concept’den kaçar tane satış gerçekleşmiş?

In [84]:
data["ConceptName"].value_counts()

Herşey Dahil      53186
Yarım Pansiyon     3559
Oda + Kahvaltı     2419
Name: ConceptName, dtype: int64

# Soru5: 
Şehirlere göre satışlardan toplam ne kadar kazanılmış?

In [ ]:
city, price

In [530]:
#Daha düzenli çıktı veriyor.
data.groupby("SaleCityName").agg({"Price": "sum"})

#Benim yaptığım.
#data.groupby(["SaleCityName"]).sum()['Price']

#df.groupby(by=['Country']).count()['Student']

                     Price
SaleCityName
Antalya       2.041911e+06
Aydın         5.732960e+05
Diğer         1.545723e+05
Girne         2.706503e+04
Muğla         6.658422e+05
İzmir         1.659348e+05

# Soru6:
 Concept türlerine göre ne kadar kazanılmış?

In [533]:
#Daha düzenli çıktı veriyor.
data.groupby("ConceptName").agg({"Price": "sum"})

#Benim yaptığım.
#data.groupby(["ConceptName"]).sum()['Price']

                       Price
ConceptName
Herşey Dahil    3.332911e+06
Oda + Kahvaltı  1.213084e+05
Yarım Pansiyon  1.744024e+05

# Soru7: 
Şehirlere göre PRICE ortalamaları nedir?

In [535]:
#Daha düzenli çıktı veriyor.
data.groupby(by=['SaleCityName']).agg({"Price": "mean"})

#Benim yaptığım.
#data.groupby(["SaleCityName"]).mean()['Price']

                  Price
SaleCityName
Antalya       64.521474
Aydın         53.855896
Diğer         47.707497
Girne         59.483579
Muğla         62.461746
İzmir         66.267905

# Soru 8: 
Conceptlere göre PRICE ortalamaları nedir

In [537]:
#Daha düzenli çıktı veriyor.
data.groupby(by=['ConceptName']).agg({"Price": "mean"})

#Benim yaptığım.
#data.groupby(["ConceptName"]).mean()['Price']

                    Price
ConceptName
Herşey Dahil    62.672260
Oda + Kahvaltı  50.252010
Yarım Pansiyon  49.030742

# Soru 9: 
Şehir-Concept kırılımındaPRICE ortalamalarınedir?

In [539]:
#Daha düzenli çıktı veriyor.
data.groupby(by=["SaleCityName", 'ConceptName']).agg({"Price": "mean"})

#Benim yaptığım.
#data.groupby(["SaleCityName", "ConceptName"]).agg({"Price":["mean"]})

                                 Price
SaleCityName ConceptName
Antalya      Herşey Dahil    64.519028
             Oda + Kahvaltı  63.504816
             Yarım Pansiyon  67.190613
Aydın        Herşey Dahil    53.995467
             Oda + Kahvaltı  34.458787
             Yarım Pansiyon  30.016543
Diğer        Herşey Dahil    84.771093
             Oda + Kahvaltı  37.599082
             Yarım Pansiyon  42.113440
Girne        Herşey Dahil    97.680970
             Oda + Kahvaltı  39.775536
             Yarım Pansiyon  53.247838
Muğla        Herşey Dahil    63.020053
             Oda + Kahvaltı  59.037763
             Yarım Pansiyon  45.120924
İzmir        Herşey Dahil    74.701519
             Oda + Kahvaltı  41.320342
             Yarım Pansiyon  59.610053

# GÖREV-2

• Satis_checkin_day_diff değişkenini EB_Score adında yeni bir kategorik değişkene çeviriniz.

• SaleCheckInDayDiff değişkeni müşterinin CheckIn tarihinden ne kadar önce satin alımını tamamladığını gösterir.
• Aralıkları ikna edici şekilde oluşturunuz.
Örneğin: ‘0_7’, ‘7_30', ‘30_90', ‘90_max’ aralıklarını kullanabilirsiniz.
• Bu aralıklar için "Last Minuters", "Potential Planners", "Planners", "Early Bookers" isimlerini kullanabilirsiniz.

NOT:
Burada "label" ve "90>" ifadesi ekleyemedim.

In [46]:
bins = [-1, 7, 30, 90, data["SaleCheckInDayDiff"].max()]
labels = ["Last Minuters", "Potential Planners", "Planners", "Early Bookers"]

In [47]:
data["EB_Score"] = pd.cut(data["SaleCheckInDayDiff"], bins, labels=labels)
data.head(50).to_excel("miuul_gezinomi.xlsx", index=False)

In [48]:
data.head(50)

,SaleId,SaleDate,CheckInDate,Price,ConceptName,SaleCityName,CInDay,SaleCheckInDayDiff,Seasons,Check_Aralık_Degeri,EB_Score
0,415122,2022-12-03,2022-12-03,79.304029,Herşey Dahil,Antalya,Saturday,0,Low,"[0, 7)",Last Minuters
1,415103,2022-12-03,2022-12-03,45.970696,Yarım Pansiyon,Antalya,Saturday,0,Low,"[0, 7)",Last Minuters
2,404034,2022-09-12,2022-09-13,77.838828,Herşey Dahil,Antalya,Tuesday,1,High,"[0, 7)",Last Minuters
3,415094,2022-12-03,2022-12-10,222.710623,Yarım Pansiyon,İzmir,Saturday,7,Low,"[7, 30)",Last Minuters
4,414951,2022-12-01,2022-12-03,140.476190,Yarım Pansiyon,İzmir,Saturday,2,Low,"[0, 7)",Last Minuters
5,415091,2022-12-03,2022-12-03,70.268620,Yarım Pansiyon,İzmir,Saturday,0,Low,"[0, 7)",Last Minuters
6,415085,2022-12-03,2022-12-09,45.787546,Yarım Pansiyon,Antalya,Friday,6,Low,"[0, 7)",Last Minuters
7,415084,2022-12-03,2022-12-03,51.239316,Herşey Dahil,Antalya,Saturday,0,Low,"[0, 7)",Last Minuters
8,415081,2022-12-03,2022-12-04,77.289377,Yarım Pansiyon,İzmir,Sunday,1,Low,"[0, 7)",Last Minuters
9,415079,2022-12-03,2022-12-03,68.681319,Yarım Pansiyon,Diğer,Saturday,0,Low,"[0, 7)",Last Minuters
10,415076,2022-12-03,2022-12-03,103.021978,Yarım Pansiyon,Diğer,Saturday,0,Low,"[0, 7)",Last Minuters
11,415078,2022-12-03,2022-12-07,39.682540,Oda + Kahvaltı,Diğer,Wednesday,4,Low,"[0, 7)",Last Minuters
12,415075,2022-12-03,2022-12-03,53.357753,Oda + Kahvaltı,İzmir,Saturday,0,Low,"[0, 7)",Last Minuters
13,415072,2022-12-03,2023-01-23,37.390527,Yarım Pansiyon,İzmir,Monday,51,Low,"[30, 90)",Planners
14,415071,2022-12-03,2022-12-03,70.268620,Yarım Pansiyon,İzmir,Saturday,0,Low,"[0, 7)",Last Minuters
15,415066,2022-12-02,2022-12-31,108.745421,Yarım Pansiyon,Diğer,Saturday,29,Low,"[7, 30)",Potential Planners
16,415066,2022-12-02,2022-12-31,144.993895,Yarım Pansiyon,Diğer,Saturday,29,Low,"[7, 30)",Potential Planners
17,415064,2022-12-02,2022-12-03,70.268620,Yarım Pansiyon,İzmir,Saturday,1,Low,"[0, 7)",Last Minuters
18,415055,2022-12-02,2022-12-03,42.572243,Yarım Pansiyon,İzmir,Saturday,1,Low,"[0, 7)",Last Minuters
19,415043,2022-12-02,2023-01-27,77.211796,Yarım Pansiyon,Diğer,Friday,56,Low,"[30, 90)",Planners
20,415041,2022-12-02,2022-12-23,122.100122,Yarım Pansiyon,Diğer,Friday,21,Low,"[7, 30)",Potential Planners
21,415031,2022-12-02,2022-12-02,42.735043,Oda + Kahvaltı,Antalya,Friday,0,Low,"[0, 7)",Last Minuters
22,415028,2022-12-02,2022-12-02,42.735043,Oda + Kahvaltı,Antalya,Friday,0,Low,"[0, 7)",Last Minuters
23,415022,2022-12-02,2022-12-03,68.681319,Yarım Pansiyon,Antalya,Saturday,1,Low,"[0, 7)",Last Minuters
24,415022,2022-12-02,2022-12-03,45.787546,Yarım Pansiyon,Antalya,Saturday,1,Low,"[0, 7)",Last Minuters
25,414992,2022-12-02,2022-12-03,73.199023,Herşey Dahil,Antalya,Saturday,1,Low,"[0, 7)",Last Minuters
26,414992,2022-12-02,2022-12-03,109.798535,Herşey Dahil,Antalya,Saturday,1,Low,"[0, 7)",Last Minuters
27,414986,2022-12-02,2022-12-10,42.735043,Oda + Kahvaltı,Antalya,Saturday,8,Low,"[7, 30)",Potential Planners
28,414968,2022-12-02,2022-12-10,63.858364,Yarım Pansiyon,İzmir,Saturday,8,Low,"[7, 30)",Potential Planners
29,414950,2022-12-01,2022-12-12,35.134310,Yarım Pansiyon,İzmir,Monday,11,Low,"[7, 30)",Potential Planners
30,414949,2022-12-01,2022-12-12,42.572243,Yarım Pansiyon,İzmir,Monday,11,Low,"[7, 30)",Potential Planners
31,414948,2022-12-01,2023-01-25,37.390527,Yarım Pansiyon,İzmir,Wednesday,55,Low,"[30, 90)",Planners
32,414912,2022-12-01,2022-12-02,40.064103,Yarım Pansiyon,Diğer,Friday,1,Low,"[0, 7)",Last Minuters
33,414816,2022-11-30,2022-12-01,45.787546,Yarım Pansiyon,Diğer,Thursday,1,Low,"[0, 7)",Last Minuters
34,414905,2022-12-01,2022-12-30,190.781441,Yarım Pansiyon,Diğer,Friday,29,Low,"[7, 30)",Potential Planners
35,190065,2018-10-10,2018-10-20,56.133056,Oda + Kahvaltı,Diğer,Saturday,10,Low,"[7, 30)",Potential Planners
36,414888,2022-12-01,2022-12-02,52.869353,Herşey Dahil,Antalya,Friday,1,Low,"[0, 7)",Last Minuters
37,414843,2022-12-01,2022-12-16,64.102564,Oda + Kahvaltı,Antalya,Friday,15,Low,"[7, 30)",Potential Planners
38,414833,2022-11-30,2022-12-26,39.682540,Oda + Kahvaltı,Diğer,Monday,26,Low,"[7, 30)",Potential Planners
39,414830,2022-11-30,2022-12-26,46.296296,Oda + Kahvaltı,Diğer,Monday,26,Low,"[7, 30)",Potential Planners
40,414829,2022-11-30,2022-12-26,36.706349,Oda + Kahvaltı,Diğer,Monday,26,Low,"[7, 30)",Potential Planners
41,414827,2022-11-30,2022-12-26,46.296296,Oda + Kahvaltı,Diğer,Monday,26,Low,"[7, 30)",Potential Planners
42,414826,2022-11-30,2022-12-03,49.868742,Oda + Kahvaltı,İzmir,Saturday,3,Low,"[0, 7)",Last Minuters
43,414824,2022-11-30,2022-12-02,59.728327,Yarım Pansiyon,İzmir,Friday,2,Low,"[0, 7)",Last Minuters
44,414823,2022-12-01,2022-12-04,40.506716,Yarım Pansiyon,Diğer,Sunday,3,Low,"[0, 7)",Last Minuters
45,414820,2022-11-30,2022-12-02,45.787546,Yarım Pansiyon,Antalya,Friday,2,Low,"[0, 7)",Last Minuters
46,414777,2022-11-30,2023-01-15,49.597855,Yarım Pansiyon,Diğer,Sunday,46,Low,"[30, 90)",Planners
47,414773,2022-11-30,2022-12-01,45.787546,Yarım Pansiyon,Diğer,Thursday,1,Low,"[0, 7)",Last Minuters
48,414764,2022-11-30,2022-12-02,109.798535,Herşey Dahil,Antalya,Friday,2,Low,"[0, 7)",Last Minuters
49,414747,2022-11-30,2023-01-21,56.300268,Yarım Pansiyon,Diğer,Saturday,52,Low,"[30, 90)",Planners

# GÖREV-3

COUNTRY, SOURCE, SEX, AGE kırılımında ortalama kazançlar nedir?

Şehir-Concept-EB Score, Şehir-Concept- Sezon, Şehir-Concept-CInDay kırılımında ortalama ödenen ücret ve yapılan işlem sayısı cinsinden
inceleyiniz ?


Not:
EB score yukarıda cut ile label oluşturamadığım için yapmadım. Diğer kırılımları nasıl ekleyeceğim bilmiyorum.

In [57]:
#Benim yaptığım:
data.groupby(["SaleCityName", "ConceptName","EB_Score"]).agg({
            "Price":["mean", "count"]})

#Hocanın yaptığı:
data.groupby(by=["SaleCityName", 'ConceptName', "EB_Score" ]).agg({"Price": ["mean", "count"]})

                                                    Price
                                                     mean  count
SaleCityName ConceptName    EB_Score
Antalya      Herşey Dahil   Last Minuters       62.752916  14148
                            Potential Planners  64.903700   8874
                            Planners            67.879960   4490
                            Early Bookers       66.494885   3281
             Oda + Kahvaltı Last Minuters       65.353740    503
                            Potential Planners  57.735542     75
                            Planners            39.851330     15
                            Early Bookers       35.002594      5
             Yarım Pansiyon Last Minuters       70.433576    204
                            Potential Planners  55.639242     39
                            Planners            58.032913      9
                            Early Bookers       35.030208      4
Aydın        Herşey Dahil   Last Minuters       51.709644   3965
                            Potential Planners  52.094045   2717
                            Planners            57.882884   1834
                            Early Bookers       57.442037   2060
             Oda + Kahvaltı Last Minuters       37.800768     20
                            Potential Planners  31.080306     15
                            Planners            30.203107      2
                            Early Bookers       26.807760      1
             Yarım Pansiyon Last Minuters       30.871015     18
                            Potential Planners  23.732060      6
                            Planners            28.806592      6
                            Early Bookers       59.602649      1
Diğer        Herşey Dahil   Last Minuters       75.465162    155
                            Potential Planners  85.791909    129
                            Planners            87.263760    120
                            Early Bookers       94.787071    101
             Oda + Kahvaltı Last Minuters       38.113403    539
                            Potential Planners  34.980158    176
...                                                   ...    ...
Girne        Oda + Kahvaltı Planners            43.151247     28
                            Early Bookers       43.965172     10
             Yarım Pansiyon Last Minuters       60.857099     73
                            Potential Planners  53.396800     81
                            Planners            45.989223     43
                            Early Bookers       33.600037     13
Muğla        Herşey Dahil   Last Minuters       63.688468   3851
                            Potential Planners  62.410423   2942
                            Planners            63.436002   1959
                            Early Bookers       61.524856   1067
             Oda + Kahvaltı Last Minuters       51.087532    331
                            Potential Planners  63.106492    149
                            Planners            72.393236    121
                            Early Bookers       66.759906     53
             Yarım Pansiyon Last Minuters       41.879531    104
                            Potential Planners  45.291786     50
                            Planners            52.802373     24
                            Early Bookers       61.143910      9
İzmir        Herşey Dahil   Last Minuters       73.248524    589
                            Potential Planners  67.773127    440
                            Planners            80.035203    231
                            Early Bookers       96.786030    121
             Oda + Kahvaltı Last Minuters       40.458855    163
                            Potential Planners  36.807772     41
                            Planners            53.159122     21
                            Early Bookers       66.928111      3
             Yarım Pansiyon Last Minuters       57.788126    636
                            Potential Planners  64.804043    198
                            Planners            60.507887     47
                            Early Bookers       65.905583     14

[72 rows x 2 columns]

In [52]:
#Şehir-Concept- Sezon
data.groupby(["SaleCityName", "ConceptName", "Seasons"]).agg({
            "Price":["mean", "count"]})

                                          Price
                                           mean  count
SaleCityName ConceptName    Seasons
Antalya      Herşey Dahil   High      64.920065  27126
                            Low       61.552427   3667
             Oda + Kahvaltı High      66.267969    303
                            Low       60.666730    295
             Yarım Pansiyon High      73.259029    118
                            Low       62.001678    138
Aydın        Herşey Dahil   High      54.946560  10103
                            Low       33.680699    473
             Oda + Kahvaltı High      30.387530     27
                            Low       44.451874     11
             Yarım Pansiyon High      32.626152     20
                            Low       25.271799     11
Diğer        Herşey Dahil   High      83.787273    364
                            Low       87.310882    141
             Oda + Kahvaltı High      34.839543    349
                            Low       39.959569    408
             Yarım Pansiyon High      39.731916    516
                            Low       42.953978   1462
Girne        Herşey Dahil   High     103.935448     55
                            Low       90.935944     51
             Oda + Kahvaltı High      39.479630     66
                            Low       40.043067     73
             Yarım Pansiyon High      58.383668    100
                            Low       48.578903    110
Muğla        Herşey Dahil   High      63.384036   9582
                            Low       48.304086    237
             Oda + Kahvaltı High      61.264691    592
                            Low       37.774192     62
             Yarım Pansiyon High      45.823698    177
                            Low       32.681812     10
İzmir        Herşey Dahil   High      74.748363   1234
                            Low       74.308287    147
             Oda + Kahvaltı High      54.141797     86
                            Low       33.555235    142
             Yarım Pansiyon High      87.657303    118
                            Low       55.350626    777

In [54]:
#Şehir-Concept-CInDay
data.groupby(["SaleCityName", "ConceptName", "CInDay"]).agg({
            "Price":["mean", "count"]})

                                           Price
                                            mean count
SaleCityName ConceptName    CInDay
Antalya      Herşey Dahil   Friday     62.658940  4136
                            Monday     63.259143  6831
                            Saturday   64.415526  4741
                            Sunday     65.849177  3818
                            Thursday   62.892734  3898
                            Tuesday    66.771658  3760
                            Wednesday  67.173832  3609
             Oda + Kahvaltı Friday     63.128165   114
                            Monday     57.172843    66
                            Saturday   58.012419   117
                            Sunday     63.469286    46
                            Thursday   64.652956    93
                            Tuesday    65.836347    73
                            Wednesday  72.809471    89
             Yarım Pansiyon Friday     69.255990    38
                            Monday     76.953874    20
                            Saturday   63.375241    71
                            Sunday     64.448325    30
                            Thursday   66.636531    40
                            Tuesday    71.019500    21
                            Wednesday  67.778590    36
Aydın        Herşey Dahil   Friday     51.034045  1825
                            Monday     54.384873  2566
                            Saturday   56.887420  1702
                            Sunday     53.194475  1098
                            Thursday   54.513836  1315
                            Tuesday    53.507135  1098
                            Wednesday  54.219028   972
             Oda + Kahvaltı Friday     31.173652     7
                            Monday     45.399902     7
...                                          ...   ...
Muğla        Oda + Kahvaltı Tuesday    50.885072    82
                            Wednesday  53.400189    98
             Yarım Pansiyon Friday     38.788744    22
                            Monday     47.982779    38
                            Saturday   48.632882    31
                            Sunday     49.876102    20
                            Thursday   37.844632    27
                            Tuesday    39.308648    28
                            Wednesday  53.967911    21
İzmir        Herşey Dahil   Friday     71.402663   170
                            Monday     73.254662   305
                            Saturday   72.857191   283
                            Sunday     75.098061   189
                            Thursday   79.071643   174
                            Tuesday    75.605713   128
                            Wednesday  79.042105   132
             Oda + Kahvaltı Friday     46.561400    25
                            Monday     43.946467    18
                            Saturday   38.638023    69
                            Sunday     42.911591    26
                            Thursday   39.367149    27
                            Tuesday    41.813607    28
                            Wednesday  41.444212    35
             Yarım Pansiyon Friday     65.380694   160
                            Monday     59.799559   102
                            Saturday   52.504725   315
                            Sunday     98.934697    68
                            Thursday   52.484894    91
                            Tuesday    56.141381    73
                            Wednesday  54.064392    86

[126 rows x 2 columns]

# GÖREV-4
 City-Concept-Season kırılımının çıktısını PRICE'a göre sıralayınız. Elde edilen çıktıyı "agg_df" olarak kayıt ediniz.
 
 
NOT:
Price ı mean na göre sıralayamadım. Direkt price ı alıp sıraladım büyükten küçüğe.

In [118]:
#Benim yaptığım:

agg_df = data[["SaleCityName", "ConceptName", "Seasons", "Price"]]
agg_df.sort_values("Price", ascending = False).head()

      SaleCityName   ConceptName Seasons        Price
41028        Aydın  Herşey Dahil    High  4880.471380
42487      Antalya  Herşey Dahil     Low  3908.701854
12975      Antalya  Herşey Dahil    High  2773.962149
38610      Antalya  Herşey Dahil    High  2735.381594
42484      Antalya  Herşey Dahil     Low  2574.893010

In [117]:
#Hocanın yaptığı: (Baya iyi)
agg_df = data.groupby(["SaleCityName", "ConceptName", "Seasons"]).agg({"Price": "mean"}).sort_values("Price", ascending=False)
agg_df.head(20)

                                          Price
SaleCityName ConceptName    Seasons
Girne        Herşey Dahil   High     103.935448
                            Low       90.935944
İzmir        Yarım Pansiyon High      87.657303
Diğer        Herşey Dahil   Low       87.310882
                            High      83.787273
İzmir        Herşey Dahil   High      74.748363
                            Low       74.308287
Antalya      Yarım Pansiyon High      73.259029
             Oda + Kahvaltı High      66.267969
             Herşey Dahil   High      64.920065
Muğla        Herşey Dahil   High      63.384036
Antalya      Yarım Pansiyon Low       62.001678
             Herşey Dahil   Low       61.552427
Muğla        Oda + Kahvaltı High      61.264691
Antalya      Oda + Kahvaltı Low       60.666730
Girne        Yarım Pansiyon High      58.383668
İzmir        Yarım Pansiyon Low       55.350626
Aydın        Herşey Dahil   High      54.946560
İzmir        Oda + Kahvaltı High      54.141797
Girne        Yarım Pansiyon Low       48.578903

# GÖREV-5
Indekste yer alan isimleri değişken ismine çeviriniz.
Üçüncü sorunun çıktısında yer alan PRICE dışındaki tüm değişkenler index isimleridir. Bu isimleri değişken isimlerine çeviriniz.

NOT:
Bu soruyu doğru yaptım mı emin değilim.

In [105]:
#Benim yaptığım:

data.index
data1 = pd.DataFrame(data, columns = ['SaleCityName','ConceptName','Seasons', 'Price'], index = ['Item_1','Item_2','Item_3','Item_4','Item_5'])

data1.reset_index(inplace=True)
data1

    index SaleCityName ConceptName Seasons  Price
0  Item_1          NaN         NaN     NaN    NaN
1  Item_2          NaN         NaN     NaN    NaN
2  Item_3          NaN         NaN     NaN    NaN
3  Item_4          NaN         NaN     NaN    NaN
4  Item_5          NaN         NaN     NaN    NaN

In [81]:
#Hocanın yaptığı:
agg_df.reset_index(inplace=True)
agg_df.head(20)

   SaleCityName     ConceptName Seasons       Price
0         Girne    Herşey Dahil    High  103.935448
1         Girne    Herşey Dahil     Low   90.935944
2         İzmir  Yarım Pansiyon    High   87.657303
3         Diğer    Herşey Dahil     Low   87.310882
4         Diğer    Herşey Dahil    High   83.787273
5         İzmir    Herşey Dahil    High   74.748363
6         İzmir    Herşey Dahil     Low   74.308287
7       Antalya  Yarım Pansiyon    High   73.259029
8       Antalya  Oda + Kahvaltı    High   66.267969
9       Antalya    Herşey Dahil    High   64.920065
10        Muğla    Herşey Dahil    High   63.384036
11      Antalya  Yarım Pansiyon     Low   62.001678
12      Antalya    Herşey Dahil     Low   61.552427
13        Muğla  Oda + Kahvaltı    High   61.264691
14      Antalya  Oda + Kahvaltı     Low   60.666730
15        Girne  Yarım Pansiyon    High   58.383668
16        İzmir  Yarım Pansiyon     Low   55.350626
17        Aydın    Herşey Dahil    High   54.946560
18        İzmir  Oda + Kahvaltı    High   54.141797
19        Girne  Yarım Pansiyon     Low   48.578903

# GÖREV-6
Yeni seviye tabanlı müşterileri (persona) tanımlayınız.

• Yeni seviye tabanlı satışları tanımlayınız ve veri setine değişken olarak ekleyiniz.
• Yeni eklenecek değişkenin adı: sales_level_based
• Önceki soruda elde edeceğiniz çıktıdaki gözlemleri bir araya getirerek sales_level_based değişkenini oluşturmanız gerekmektedir.

In [156]:
#Benim yaptığım:

data2=data[['SaleCityName','ConceptName','Seasons', 'Price']]
data2['sales_level_based'] = data2[['SaleCityName','ConceptName','Seasons']].agg(' _ '.join, axis=1)
data2.head(20)

C:\Users\HP-PC\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,SaleCityName,ConceptName,Seasons,Price,sales_level_based
0,Antalya,Herşey Dahil,Low,79.304029,Antalya _ Herşey Dahil _ Low
1,Antalya,Yarım Pansiyon,Low,45.970696,Antalya _ Yarım Pansiyon _ Low
2,Antalya,Herşey Dahil,High,77.838828,Antalya _ Herşey Dahil _ High
3,İzmir,Yarım Pansiyon,Low,222.710623,İzmir _ Yarım Pansiyon _ Low
4,İzmir,Yarım Pansiyon,Low,140.476190,İzmir _ Yarım Pansiyon _ Low
5,İzmir,Yarım Pansiyon,Low,70.268620,İzmir _ Yarım Pansiyon _ Low
6,Antalya,Yarım Pansiyon,Low,45.787546,Antalya _ Yarım Pansiyon _ Low
7,Antalya,Herşey Dahil,Low,51.239316,Antalya _ Herşey Dahil _ Low
8,İzmir,Yarım Pansiyon,Low,77.289377,İzmir _ Yarım Pansiyon _ Low
9,Diğer,Yarım Pansiyon,Low,68.681319,Diğer _ Yarım Pansiyon _ Low
10,Diğer,Yarım Pansiyon,Low,103.021978,Diğer _ Yarım Pansiyon _ Low
11,Diğer,Oda + Kahvaltı,Low,39.682540,Diğer _ Oda + Kahvaltı _ Low
12,İzmir,Oda + Kahvaltı,Low,53.357753,İzmir _ Oda + Kahvaltı _ Low
13,İzmir,Yarım Pansiyon,Low,37.390527,İzmir _ Yarım Pansiyon _ Low
14,İzmir,Yarım Pansiyon,Low,70.268620,İzmir _ Yarım Pansiyon _ Low
15,Diğer,Yarım Pansiyon,Low,108.745421,Diğer _ Yarım Pansiyon _ Low
16,Diğer,Yarım Pansiyon,Low,144.993895,Diğer _ Yarım Pansiyon _ Low
17,İzmir,Yarım Pansiyon,Low,70.268620,İzmir _ Yarım Pansiyon _ Low
18,İzmir,Yarım Pansiyon,Low,42.572243,İzmir _ Yarım Pansiyon _ Low
19,Diğer,Yarım Pansiyon,Low,77.211796,Diğer _ Yarım Pansiyon _ Low

In [127]:
#Hocanın yaptığı:
agg_df['sales_level_based'] = agg_df[["SaleCityName", "ConceptName", "Seasons"]].agg(lambda x: '_'.join(x).upper(), axis=1)
agg_df.head(20)

,SaleCityName,ConceptName,Seasons,Price,sales_level_based
0,Antalya,Herşey Dahil,Low,79.304029,ANTALYA_HERŞEY DAHIL_LOW
1,Antalya,Yarım Pansiyon,Low,45.970696,ANTALYA_YARIM PANSIYON_LOW
2,Antalya,Herşey Dahil,High,77.838828,ANTALYA_HERŞEY DAHIL_HIGH
3,İzmir,Yarım Pansiyon,Low,222.710623,İZMIR_YARIM PANSIYON_LOW
4,İzmir,Yarım Pansiyon,Low,140.476190,İZMIR_YARIM PANSIYON_LOW
5,İzmir,Yarım Pansiyon,Low,70.268620,İZMIR_YARIM PANSIYON_LOW
6,Antalya,Yarım Pansiyon,Low,45.787546,ANTALYA_YARIM PANSIYON_LOW
7,Antalya,Herşey Dahil,Low,51.239316,ANTALYA_HERŞEY DAHIL_LOW
8,İzmir,Yarım Pansiyon,Low,77.289377,İZMIR_YARIM PANSIYON_LOW
9,Diğer,Yarım Pansiyon,Low,68.681319,DIĞER_YARIM PANSIYON_LOW
10,Diğer,Yarım Pansiyon,Low,103.021978,DIĞER_YARIM PANSIYON_LOW
11,Diğer,Oda + Kahvaltı,Low,39.682540,DIĞER_ODA + KAHVALTI_LOW
12,İzmir,Oda + Kahvaltı,Low,53.357753,İZMIR_ODA + KAHVALTI_LOW
13,İzmir,Yarım Pansiyon,Low,37.390527,İZMIR_YARIM PANSIYON_LOW
14,İzmir,Yarım Pansiyon,Low,70.268620,İZMIR_YARIM PANSIYON_LOW
15,Diğer,Yarım Pansiyon,Low,108.745421,DIĞER_YARIM PANSIYON_LOW
16,Diğer,Yarım Pansiyon,Low,144.993895,DIĞER_YARIM PANSIYON_LOW
17,İzmir,Yarım Pansiyon,Low,70.268620,İZMIR_YARIM PANSIYON_LOW
18,İzmir,Yarım Pansiyon,Low,42.572243,İZMIR_YARIM PANSIYON_LOW
19,Diğer,Yarım Pansiyon,Low,77.211796,DIĞER_YARIM PANSIYON_LOW

# Görev 7:
    
Yeni müşterileri (personaları) segmentlere ayırınız.

• Yeni personaları PRICE’a göre 4 segmente ayırınız.
• Segmentleri SEGMENT isimlendirmesi ile değişken olarak agg_df’e ekleyiniz.
• Segmentleri betimleyiniz (Segmentlere göre group by yapıp price mean, max, sum’larını alınız)

In [134]:
#Benim yaptığım:

SEGMENT=["D", "C", "B", "A"]
data["agg_df"] = pd.qcut(data.Price, q=4, labels=["D", "C", "B", "A"])
data.groupby("agg_df").agg({"Price":["mean", "max", "sum"]})

             Price
              mean          max           sum
agg_df
D        25.659182    35.343035  3.794480e+05
C        44.597904    54.261294  6.596030e+05
B        64.975656    77.962578  9.607300e+05
A       110.153543  4880.471380  1.628840e+06

In [135]:
#Hocanın yaptığı:

agg_df["SEGMENT"] = pd.qcut(agg_df["Price"], 4, labels=["D", "C", "B", "A"])
agg_df.head(30)
agg_df.groupby("SEGMENT").agg({"Price": ["mean", "max", "sum"]})

              Price
               mean          max           sum
SEGMENT
D         25.659182    35.343035  3.794480e+05
C         44.597904    54.261294  6.596030e+05
B         64.975656    77.962578  9.607300e+05
A        110.153543  4880.471380  1.628840e+06

In [136]:
agg_df

,SaleCityName,ConceptName,Seasons,Price,sales_level_based,SEGMENT
0,Antalya,Herşey Dahil,Low,79.304029,ANTALYA_HERŞEY DAHIL_LOW,A
1,Antalya,Yarım Pansiyon,Low,45.970696,ANTALYA_YARIM PANSIYON_LOW,C
2,Antalya,Herşey Dahil,High,77.838828,ANTALYA_HERŞEY DAHIL_HIGH,B
3,İzmir,Yarım Pansiyon,Low,222.710623,İZMIR_YARIM PANSIYON_LOW,A
4,İzmir,Yarım Pansiyon,Low,140.476190,İZMIR_YARIM PANSIYON_LOW,A
5,İzmir,Yarım Pansiyon,Low,70.268620,İZMIR_YARIM PANSIYON_LOW,B
6,Antalya,Yarım Pansiyon,Low,45.787546,ANTALYA_YARIM PANSIYON_LOW,C
7,Antalya,Herşey Dahil,Low,51.239316,ANTALYA_HERŞEY DAHIL_LOW,C
8,İzmir,Yarım Pansiyon,Low,77.289377,İZMIR_YARIM PANSIYON_LOW,B
9,Diğer,Yarım Pansiyon,Low,68.681319,DIĞER_YARIM PANSIYON_LOW,B
10,Diğer,Yarım Pansiyon,Low,103.021978,DIĞER_YARIM PANSIYON_LOW,A
11,Diğer,Oda + Kahvaltı,Low,39.682540,DIĞER_ODA + KAHVALTI_LOW,C
12,İzmir,Oda + Kahvaltı,Low,53.357753,İZMIR_ODA + KAHVALTI_LOW,C
13,İzmir,Yarım Pansiyon,Low,37.390527,İZMIR_YARIM PANSIYON_LOW,C
14,İzmir,Yarım Pansiyon,Low,70.268620,İZMIR_YARIM PANSIYON_LOW,B
15,Diğer,Yarım Pansiyon,Low,108.745421,DIĞER_YARIM PANSIYON_LOW,A
16,Diğer,Yarım Pansiyon,Low,144.993895,DIĞER_YARIM PANSIYON_LOW,A
17,İzmir,Yarım Pansiyon,Low,70.268620,İZMIR_YARIM PANSIYON_LOW,B
18,İzmir,Yarım Pansiyon,Low,42.572243,İZMIR_YARIM PANSIYON_LOW,C
19,Diğer,Yarım Pansiyon,Low,77.211796,DIĞER_YARIM PANSIYON_LOW,B
20,Diğer,Yarım Pansiyon,Low,122.100122,DIĞER_YARIM PANSIYON_LOW,A
21,Antalya,Oda + Kahvaltı,Low,42.735043,ANTALYA_ODA + KAHVALTI_LOW,C
22,Antalya,Oda + Kahvaltı,Low,42.735043,ANTALYA_ODA + KAHVALTI_LOW,C
23,Antalya,Yarım Pansiyon,Low,68.681319,ANTALYA_YARIM PANSIYON_LOW,B
24,Antalya,Yarım Pansiyon,Low,45.787546,ANTALYA_YARIM PANSIYON_LOW,C
25,Antalya,Herşey Dahil,Low,73.199023,ANTALYA_HERŞEY DAHIL_LOW,B
26,Antalya,Herşey Dahil,Low,109.798535,ANTALYA_HERŞEY DAHIL_LOW,A
27,Antalya,Oda + Kahvaltı,Low,42.735043,ANTALYA_ODA + KAHVALTI_LOW,C
28,İzmir,Yarım Pansiyon,Low,63.858364,İZMIR_YARIM PANSIYON_LOW,B
29,İzmir,Yarım Pansiyon,Low,35.134310,İZMIR_YARIM PANSIYON_LOW,D
...,...,...,...,...,...,...
59134,Diğer,Herşey Dahil,High,88.079470,DIĞER_HERŞEY DAHIL_HIGH,A
59135,Antalya,Herşey Dahil,Low,54.304636,ANTALYA_HERŞEY DAHIL_LOW,B
59136,Girne,Yarım Pansiyon,Low,69.536424,GIRNE_YARIM PANSIYON_LOW,B
59137,Antalya,Herşey Dahil,High,144.039735,ANTALYA_HERŞEY DAHIL_HIGH,A
59138,Antalya,Herşey Dahil,Low,72.847682,ANTALYA_HERŞEY DAHIL_LOW,B
59139,Antalya,Herşey Dahil,High,69.081126,ANTALYA_HERŞEY DAHIL_HIGH,B
59140,Antalya,Herşey Dahil,High,46.054084,ANTALYA_HERŞEY DAHIL_HIGH,C
59141,Antalya,Herşey Dahil,Low,59.271523,ANTALYA_HERŞEY DAHIL_LOW,B
59142,Girne,Yarım Pansiyon,Low,36.423841,GIRNE_YARIM PANSIYON_LOW,C
59143,Girne,Yarım Pansiyon,Low,36.423841,GIRNE_YARIM PANSIYON_LOW,C
59144,Antalya,Herşey Dahil,Low,54.304636,ANTALYA_HERŞEY DAHIL_LOW,B
59145,Antalya,Herşey Dahil,High,41.757174,ANTALYA_HERŞEY DAHIL_HIGH,C
59146,Antalya,Herşey Dahil,High,41.757174,ANTALYA_HERŞEY DAHIL_HIGH,C
59147,Girne,Herşey Dahil,Low,100.303532,GIRNE_HERŞEY DAHIL_LOW,A
59148,Muğla,Herşey Dahil,High,64.017660,MUĞLA_HERŞEY DAHIL_HIGH,B
59149,Antalya,Herşey Dahil,Low,54.304636,ANTALYA_HERŞEY DAHIL_LOW,B
59150,Girne,Herşey Dahil,High,120.624409,GIRNE_HERŞEY DAHIL_HIGH,A
59151,Antalya,Herşey Dahil,Low,59.823400,ANTALYA_HERŞEY DAHIL_LOW,B
59152,Antalya,Herşey Dahil,Low,54.304636,ANTALYA_HERŞEY DAHIL_LOW,B
59153,Girne,Herşey Dahil,High,120.624409,GIRNE_HERŞEY DAHIL_HIGH,A
59154,Antalya,Herşey Dahil,Low,54.304636,ANTALYA_HERŞEY DAHIL_LOW,B
59155,Antalya,Herşey Dahil,Low,54.304636,ANTALYA_HERŞEY DAHIL_LOW,B
59156,Antalya,Herşey Dahil,Low,54.304636,ANTALYA_HERŞEY DAHIL_LOW,B
59157,Antalya,Herşey Dahil,Low,54.304636,ANTALYA_HERŞEY DAHIL_LOW,B
59158,Antalya,Herşey Dahil,Low,54.304636,ANTALYA_HERŞEY DAHIL_LOW,B
59159,Antalya,Herşey Dahil,Low,54.304636,ANTALYA_HERŞEY DAHIL_LOW,B
59160,Antalya,Herşey Dahil,Low,54.304636,ANTALYA_HERŞEY DAHIL_LOW,B
59161,Diğer,Herşey Dahil,Low,40.562914,DIĞER_HERŞEY DAHIL_LOW,C
59162,Diğer,Yarım Pansiyon,Low,69.847682,DIĞER_YARIM PANSIYON_LOW,B
59163,Antalya,Herşey Dahil,High,158.940397,ANTALYA_HERŞEY DAHIL_HIGH,A

# Görev 8: 
Yeni gelen müşterileri sınıflandırıp, ne kadar gelir getirebileceklerini tahmin ediniz.

• Antalya’da herşey dahil ve yüksek sezonda tatil yapmak isteyen bir kişinin ortalama ne kadar gelir kazandırması beklenir?
• Girne’de yarım pansiyon bir otele düşük sezonda giden bir tatilci hangi segmentte yer alacaktır?

In [148]:
#Benim yaptığım:

new_user = "Antalya_Herşey_Dahil_High"
data2[data2["sales_level_based"]==new_user]

Empty DataFrame
Columns: [SaleCityName, ConceptName, Seasons, Price, sales_level_based]
Index: []

In [150]:
#Hocanın yaptığı

In [151]:
agg_df.sort_values(by="Price").head()

,SaleCityName,ConceptName,Seasons,Price,sales_level_based,SEGMENT
51094,Girne,Yarım Pansiyon,High,0.000000,GIRNE_YARIM PANSIYON_HIGH,D
501,Antalya,Herşey Dahil,Low,0.000000,ANTALYA_HERŞEY DAHIL_LOW,D
51800,Antalya,Herşey Dahil,Low,0.000000,ANTALYA_HERŞEY DAHIL_LOW,D
502,Antalya,Herşey Dahil,Low,0.000000,ANTALYA_HERŞEY DAHIL_LOW,D
18054,Antalya,Herşey Dahil,High,0.028058,ANTALYA_HERŞEY DAHIL_HIGH,D

In [153]:
new_user = "ANTALYA_HERŞEY DAHIL_HIGH"
agg_df[agg_df["sales_level_based"] == new_user].head(1)

,SaleCityName,ConceptName,Seasons,Price,sales_level_based,SEGMENT
2,Antalya,Herşey Dahil,High,77.838828,ANTALYA_HERŞEY DAHIL_HIGH,B

In [155]:
new_user_1 = "GIRNE_YARIM PANSIYON_LOW"
agg_df[agg_df["sales_level_based"] == new_user_1].head(1)

,SaleCityName,ConceptName,Seasons,Price,sales_level_based,SEGMENT
671,Girne,Yarım Pansiyon,Low,101.343101,GIRNE_YARIM PANSIYON_LOW,A